"use client";

import {
  RiAddLine,
  RiArrowDownSLine,
  RiCheckLine,
  RiCodeBoxLine,
  RiCpuLine,
  RiDeleteBinLine,
  RiFileTextLine,
  RiFolderOpenLine,
  RiGlobalLine,
  RiKey2Line,
  RiLinksLine,
  RiRefreshLine,
  RiSettings3Line,
  RiShieldCheckLine,
  RiSparklingLine,
  RiTerminalBoxLine,
  RiToolsLine,
} from "@remixicon/react";
import { useState } from "react";
import { Button } from "@/components/base/buttons/button";
import { IconButton } from "@/components/base/buttons/icon-button";
import { InputBase } from "@/components/base/input/input";
import { Switch } from "@/components/base/switch/switch";
import { Textarea } from "@/components/base/textarea/textarea";
import { Dropdown, DropdownItem, DropdownPopover, DropdownTrigger } from "@/components/base/dropdown/dropdown";
import { ThemeToggle } from "@/components/application/theme/theme-toggle";
import type { AgentMcpServer, AgentProvider, AgentSettings } from "./workspace-store";
import type { SettingsSection } from "./workspace-sidebar";

interface Props {
  section: SettingsSection;
  settings: AgentSettings;
  onSettingsChange: (change: Partial<AgentSettings>) => void;
}

const providerPresets: Array<{ type: AgentProvider["type"]; name: string; baseUrl: string; model: string }> = [
  { type: "anthropic", name: "Anthropic", baseUrl: "https://api.anthropic.com", model: "claude-sonnet-4" },
  { type: "google", name: "Google", baseUrl: "https://generativelanguage.googleapis.com", model: "gemini-2.5-pro" },
  { type: "openai-compatible", name: "OpenAI Compatible", baseUrl: "", model: "" },
  { type: "local", name: "本地模型", baseUrl: "http://localhost:11434/v1", model: "" },
];

function updateProvider(settings: AgentSettings, providerId: string, update: Partial<AgentProvider>) {
  return settings.providers.map((provider) => provider.id === providerId ? { ...provider, ...update } : provider);
}

function SectionHeading({ icon: Icon, title, description }: { icon: typeof RiSettings3Line; title: string; description: string }) {
  return <div className="settings-section-heading"><Icon aria-hidden /><div><h3>{title}</h3><p>{description}</p></div></div>;
}

function ToggleRow({ label, detail, selected, onChange }: { label: string; detail?: string; selected: boolean; onChange: (value: boolean) => void }) {
  return <label className="settings-toggle-row"><span><strong>{label}</strong>{detail && <small>{detail}</small>}</span><Switch size="sm" aria-label={label} isSelected={selected} onChange={onChange} /></label>;
}

function ChoiceField<T extends string | number>({ label, value, options, onChange }: { label: string; value: T; options: Array<{ value: T; label: string }>; onChange: (value: T) => void }) {
  const selected = options.find((option) => option.value === value) ?? options[0];
  return <div className="settings-choice-row"><span>{label}</span><Dropdown><DropdownTrigger className="settings-choice-trigger" aria-label={label}>{selected?.label ?? "选择"}<RiArrowDownSLine aria-hidden /></DropdownTrigger><DropdownPopover aria-label={label} placement="bottom end">{options.map((option) => <DropdownItem key={String(option.value)} selected={option.value === value} onSelect={() => onChange(option.value)}>{option.label}</DropdownItem>)}</DropdownPopover></Dropdown></div>;
}

function ProviderPanel({ settings, onSettingsChange }: { settings: AgentSettings; onSettingsChange: Props["onSettingsChange"] }) {
  const provider = settings.providers.find((item) => item.id === settings.activeProviderId) ?? settings.providers[0];
  function addProvider(type: AgentProvider["type"]) {
    const preset = providerPresets.find((item) => item.type === type);
    if (!preset || settings.providers.some((item) => item.type === type)) return;
    const next: AgentProvider = { id: `${type}-${settings.providers.length + 1}`, ...preset, apiKey: "", enabled: true, status: "not_configured" };
    onSettingsChange({ providers: [...settings.providers, next], activeProviderId: next.id, model: next.model });
  }
  function updateCurrent(update: Partial<AgentProvider>) {
    if (!provider) return;
    onSettingsChange({ providers: updateProvider(settings, provider.id, update) });
  }
  return <>
    <div className="agent-runtime-banner"><div><span className="agent-runtime-dot" />Agent Runtime</div><small>{provider?.status === "ready" ? "已配置模型，可启动会话" : "等待模型连接"}</small></div>
    <div className="provider-switcher"><label htmlFor="active-provider">主模型提供商</label><select id="active-provider" value={provider?.id ?? ""} onChange={(event) => { const next = settings.providers.find((item) => item.id === event.target.value); onSettingsChange({ activeProviderId: event.target.value, model: next?.model ?? "" }); }} aria-label="主模型提供商">{settings.providers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    <div className="provider-add-row"><span>添加连接</span>{providerPresets.map((preset) => <Button key={preset.type} size="xs" variant="secondary" disabled={settings.providers.some((item) => item.type === preset.type)} onClick={() => addProvider(preset.type)}>{preset.name}</Button>)}</div>
    {provider && <div className="provider-editor"><div className="provider-line"><label htmlFor="provider-name">连接名称</label><span className={`provider-status provider-status-${provider.status}`}>{provider.status === "ready" ? "已连接" : "未配置"}</span></div><InputBase id="provider-name" size="small" value={provider.name} onChange={(event) => updateCurrent({ name: event.target.value })} aria-label="连接名称" /><div className="settings-field-grid"><label><span>API 地址</span><InputBase size="small" value={provider.baseUrl} onChange={(event) => updateCurrent({ baseUrl: event.target.value })} aria-label="API 地址" /></label><label><span>默认模型</span><InputBase size="small" value={provider.model} onChange={(event) => { updateCurrent({ model: event.target.value }); onSettingsChange({ model: event.target.value }); }} aria-label="默认模型" /></label></div><label className="settings-secret"><span><RiKey2Line aria-hidden />API Key</span><InputBase size="small" type="password" value={provider.apiKey} onChange={(event) => updateCurrent({ apiKey: event.target.value, status: event.target.value ? "ready" : "not_configured" })} placeholder="粘贴到本地配置" aria-label="API Key" /></label><Button size="small" variant="secondary" leadingIcon={RiCheckLine} onClick={() => updateCurrent({ status: provider.apiKey ? "ready" : "not_configured" })}>保存连接</Button></div>}
    <div className="settings-subsection"><h4>模型路由</h4><ChoiceField label="推理强度" value={settings.reasoningEffort} options={[{ value: "low", label: "低：快速响应" }, { value: "medium", label: "中：平衡" }, { value: "high", label: "高：复杂任务" }]} onChange={(value) => onSettingsChange({ reasoningEffort: value as AgentSettings["reasoningEffort"] })} /><div className="settings-choice-row"><span>备用模型</span><InputBase size="small" value={settings.providers.find((item) => item.id !== settings.activeProviderId)?.model ?? ""} onChange={(event) => { const fallback = settings.providers.find((item) => item.id !== settings.activeProviderId); if (fallback) onSettingsChange({ providers: updateProvider(settings, fallback.id, { model: event.target.value }) }); }} placeholder="可选" aria-label="备用模型" /></div><ChoiceField label="响应语言" value={settings.responseLanguage} options={[{ value: "auto", label: "跟随输入" }, { value: "zh-CN", label: "简体中文" }, { value: "en-US", label: "English" }]} onChange={(value) => onSettingsChange({ responseLanguage: value as AgentSettings["responseLanguage"] })} /></div>
  </>;
}

function McpPanel({ settings, onSettingsChange }: { settings: AgentSettings; onSettingsChange: Props["onSettingsChange"] }) {
  const [draftName, setDraftName] = useState("");
  const [draftEndpoint, setDraftEndpoint] = useState("");
  function updateServer(id: string, update: Partial<AgentMcpServer>) { onSettingsChange({ mcpServers: settings.mcpServers.map((server) => server.id === id ? { ...server, ...update } : server) }); }
  function addServer() { if (!draftName.trim() || !draftEndpoint.trim()) return; const server: AgentMcpServer = { id: `mcp-${settings.mcpServers.length + 1}`, name: draftName.trim(), transport: "http", endpoint: draftEndpoint.trim(), enabled: false, requireApproval: true, status: "disconnected", allowedTools: [] }; onSettingsChange({ mcpServers: [...settings.mcpServers, server] }); setDraftName(""); setDraftEndpoint(""); }
  return <><div className="settings-mcp-list">{settings.mcpServers.map((server) => <div className="settings-mcp-server" key={server.id}><div className="settings-mcp-server-head"><div><strong>{server.name}</strong><small>{server.transport.toUpperCase()} · {server.status === "connected" ? "已连接" : "未连接"}</small></div><Switch size="sm" aria-label={`${server.enabled ? "停用" : "启用"}${server.name}`} isSelected={server.enabled} onChange={(next) => updateServer(server.id, { enabled: next, status: next ? "connected" : "disconnected" })} /></div><InputBase size="small" value={server.endpoint} onChange={(event) => updateServer(server.id, { endpoint: event.target.value })} aria-label={`${server.name}连接地址`} /><div className="settings-mcp-actions"><ToggleRow label="工具调用前请求确认" selected={server.requireApproval} onChange={(next) => updateServer(server.id, { requireApproval: next })} /><IconButton icon={RiDeleteBinLine} size="small" aria-label={`删除${server.name}`} onClick={() => onSettingsChange({ mcpServers: settings.mcpServers.filter((item) => item.id !== server.id) })} /></div></div>)}</div><div className="settings-add-form"><InputBase size="small" value={draftName} onChange={(event) => setDraftName(event.target.value)} placeholder="服务器名称" aria-label="MCP 服务器名称" /><InputBase size="small" value={draftEndpoint} onChange={(event) => setDraftEndpoint(event.target.value)} placeholder="HTTP 地址或 stdio 命令" aria-label="MCP 服务器地址" /><Button size="small" variant="secondary" leadingIcon={RiAddLine} onClick={addServer}>添加服务器</Button></div></>;
}

function ConnectionRow({ label, detail, status, enabled, onChange }: { label: string; detail: string; status: string; enabled?: boolean; onChange?: (value: boolean) => void }) {
  return <div className="connection-row"><div><strong>{label}</strong><small>{detail}</small></div><div className="connection-row-end"><span className={`provider-status provider-status-${status === "已连接" ? "ready" : "not_configured"}`}>{status}</span>{typeof enabled === "boolean" && onChange && <Switch size="sm" aria-label={`${enabled ? "停用" : "启用"}${label}`} isSelected={enabled} onChange={onChange} />}</div></div>;
}

export function WorkspaceAgentSettings({ section, settings, onSettingsChange }: Props) {
  const updateWorkspace = (change: Partial<AgentSettings["workspace"]>) => onSettingsChange({ workspace: { ...settings.workspace, ...change } });
  const updateTool = (key: string, value: boolean) => onSettingsChange({ tools: { ...settings.tools, [key]: value } });

  if (section === "models") return <section className="settings-section"><SectionHeading icon={RiCpuLine} title="模型与 API" description="Agent 的模型、供应商和推理路由。" /><ProviderPanel settings={settings} onSettingsChange={onSettingsChange} /></section>;
  if (section === "mcp") return <section className="settings-section"><SectionHeading icon={RiLinksLine} title="MCP 服务器" description="连接你主动配置的外部工具服务器；每个服务器都可以单独启用和审批。" /><McpPanel settings={settings} onSettingsChange={onSettingsChange} /></section>;
  if (section === "permissions") return <section className="settings-section"><SectionHeading icon={RiShieldCheckLine} title="权限与安全" description="审批、沙箱和联网权限决定 Agent 可以触碰什么。" /><div className="settings-options"><ChoiceField label="运行权限模式" value={settings.permissionMode} options={[{ value: "auto", label: "自动：高风险操作请求确认" }, { value: "manual", label: "手动：每次修改前确认" }, { value: "plan", label: "计划模式：先审阅计划" }, { value: "bypass", label: "全部跳过：自动执行" }]} onChange={(value) => onSettingsChange({ permissionMode: value as AgentSettings["permissionMode"] })} /><ChoiceField label="审批策略" value={settings.approvalPolicy} options={[{ value: "on-request", label: "需要时请求确认" }, { value: "never", label: "不请求确认" }]} onChange={(value) => onSettingsChange({ approvalPolicy: value as AgentSettings["approvalPolicy"] })} /><ChoiceField label="文件沙箱" value={settings.sandboxMode} options={[{ value: "read-only", label: "只读项目" }, { value: "workspace-write", label: "项目内可写" }, { value: "danger-full-access", label: "完全访问（谨慎）" }]} onChange={(value) => onSettingsChange({ sandboxMode: value as AgentSettings["sandboxMode"] })} /><ToggleRow label="允许联网" detail="仅在工具或模型路由需要时使用网络" selected={settings.networkAccess} onChange={(value) => onSettingsChange({ networkAccess: value })} /><ToggleRow label="启用 Web Search" selected={settings.webSearch} onChange={(value) => { updateTool("web-search", value); onSettingsChange({ webSearch: value }); }} /><ToggleRow label="记录 Agent 事件" detail="保存工具调用、审批和版本事件，方便排查" selected={settings.eventLogging} onChange={(value) => onSettingsChange({ eventLogging: value })} /></div></section>;
  if (section === "tools") return <section className="settings-section"><SectionHeading icon={RiToolsLine} title="工具与 MCP" description="每个工具都对应 Agent 的一个可执行能力。关闭后不会进入当前会话。" /><div className="tool-toggle-grid">{Object.entries({ "visual-targeting": "视觉定位：点选和框选元素", "artifact-preview": "页面预览：读取右侧作品", "file-read": "文件读取：访问项目内容", "file-write": "文件写入：修改项目文件", "version-control": "版本管理：保存和回退", export: "导出作品：生成交付文件", "web-search": "Web Search：查找外部资料", mcp: "MCP：调用已配置的外部工具" }).map(([key, label]) => <ToggleRow key={key} label={label} selected={Boolean(settings.tools[key])} onChange={(value) => updateTool(key, value)} />)}</div><div className="settings-inline"><ChoiceField label="上下文策略" value={settings.contextWindow} options={[{ value: "auto", label: "自动压缩" }, { value: "compact", label: "优先精简" }, { value: "full", label: "尽量保留" }]} onChange={(value) => onSettingsChange({ contextWindow: value as AgentSettings["contextWindow"] })} /><ChoiceField label="最大工具调用" value={settings.maxToolCalls} options={[{ value: 6, label: "6 次" }, { value: 12, label: "12 次" }, { value: 24, label: "24 次" }]} onChange={(value) => onSettingsChange({ maxToolCalls: Number(value) })} /></div></section>;
  if (section === "instructions") return <section className="settings-section"><SectionHeading icon={RiSparklingLine} title="Agent 指令" description="系统指令会和当前项目、作品选择、批注与技能一起组成 Agent 上下文。" /><Textarea label="系统指令" rows={7} value={settings.systemInstructions} onChange={(value) => onSettingsChange({ systemInstructions: value })} /><div className="settings-instruction-list"><ToggleRow label="先理解目标再行动" selected={true} onChange={() => undefined} /><ToggleRow label="修改前保存版本" selected={Boolean(settings.tools["version-control"])} onChange={(value) => updateTool("version-control", value)} /><ToggleRow label="工具调用后解释结果" selected={settings.eventLogging} onChange={(value) => onSettingsChange({ eventLogging: value })} /></div></section>;
  if (section === "workspace") return <section className="settings-section"><SectionHeading icon={RiFolderOpenLine} title="项目工作区" description="Agent 的文件读取、写入和版本记录都受项目范围约束。" /><div className="settings-field-stack"><label><span>默认工作区路径</span><InputBase size="small" value={settings.workspace.defaultPath} onChange={(event) => updateWorkspace({ defaultPath: event.target.value })} placeholder="打开项目后自动记住" aria-label="默认工作区路径" /></label><ChoiceField label="文件范围" value={settings.workspace.fileScope} options={[{ value: "project", label: "仅当前项目" }, { value: "project-and-children", label: "项目及子目录" }]} onChange={(value) => updateWorkspace({ fileScope: value as AgentSettings["workspace"]["fileScope"] })} /><ToggleRow label="每次修改自动保存版本" selected={settings.workspace.autoSaveVersions} onChange={(value) => updateWorkspace({ autoSaveVersions: value })} /></div></section>;
  if (section === "shortcuts") return <section className="settings-section"><SectionHeading icon={RiCodeBoxLine} title="键盘快捷键" description="快捷键直接作用于当前工作区，不会打断 Agent 会话。" /><div className="settings-field-stack">{Object.entries({ newConversation: "新对话", sendMessage: "发送消息", toggleTargeting: "切换点选模式", openPreview: "打开预览", stopRun: "停止 Agent" }).map(([key, label]) => <label key={key}><span>{label}</span><InputBase size="small" value={settings.shortcuts[key] ?? ""} onChange={(event) => onSettingsChange({ shortcuts: { ...settings.shortcuts, [key]: event.target.value } })} aria-label={label} /></label>)}</div></section>;
  if (section === "general") return <section className="settings-section"><SectionHeading icon={RiSettings3Line} title="Agent 运行总览" description="这是当前 Agent 会话的默认运行合同。" /><div className="agent-overview-grid"><div><span>会话</span><strong>{settings.resumeSessions ? "可恢复" : "单次运行"}</strong></div><div><span>上下文</span><strong>{settings.contextWindow === "auto" ? "自动压缩" : settings.contextWindow === "full" ? "尽量保留" : "优先精简"}</strong></div><div><span>工具上限</span><strong>{settings.maxToolCalls} 次</strong></div><div><span>事件流</span><strong>{settings.eventLogging ? "已记录" : "关闭"}</strong></div></div><ToggleRow label="恢复未完成会话" detail="重新打开项目后保留 Agent 的任务上下文" selected={settings.resumeSessions} onChange={(value) => onSettingsChange({ resumeSessions: value })} /><ToggleRow label="启用多 Agent 协作" detail="让主 Agent 将独立任务交给专门的子 Agent" selected={settings.multiAgent} onChange={(value) => onSettingsChange({ multiAgent: value })} /></section>;
  if (section === "appearance") return <section className="settings-section"><SectionHeading icon={RiGlobalLine} title="外观" description="只影响工作区，不改变导出的作品。" /><div className="settings-appearance-row"><span>主题</span><ThemeToggle appearance="segmented" /></div><ChoiceField label="界面密度" value="comfortable" options={[{ value: "comfortable", label: "舒适" }, { value: "compact", label: "紧凑" }]} onChange={() => undefined} /></section>;
  if (section === "preview") return <section className="settings-section"><SectionHeading icon={RiGlobalLine} title="网页预览" description="右侧预览是 Agent 的视觉工作面，所有定位和版本操作都围绕当前作品进行。" /><div className="settings-options"><ToggleRow label="启用作品预览" detail="生成作品后自动打开右侧预览区" selected={Boolean(settings.tools["artifact-preview"])} onChange={(value) => updateTool("artifact-preview", value)} /><ToggleRow label="允许点选和框选" detail="把元素名称、文本、尺寸和坐标写入下一条消息" selected={Boolean(settings.tools["visual-targeting"])} onChange={(value) => updateTool("visual-targeting", value)} /><ToggleRow label="保留版本快照" detail="每次修改前保存可回退的作品版本" selected={Boolean(settings.tools["version-control"])} onChange={(value) => updateTool("version-control", value)} /><ChoiceField label="上下文策略" value={settings.contextWindow} options={[{ value: "auto", label: "自动带入当前选择" }, { value: "compact", label: "只带入选中区域" }, { value: "full", label: "带入整页结构" }]} onChange={(value) => onSettingsChange({ contextWindow: value as AgentSettings["contextWindow"] })} /></div><div className="settings-inline-note"><strong>定位反馈</strong><span>已选中的元素会显示名称、可见文字、尺寸和坐标，不依赖颜色判断。</span></div></section>;
  if (section === "exports") return <section className="settings-section"><SectionHeading icon={RiFileTextLine} title="文件导出" description="Agent 根据生成内容和你的指令决定导出方式，不限制文件格式。" /><div className="settings-options"><ToggleRow label="启用导出工具" detail="允许 Agent 生成并保存任意交付文件" selected={Boolean(settings.tools.export)} onChange={(value) => updateTool("export", value)} /><ToggleRow label="导出前请求确认" detail="避免把未检查的结果直接写入项目目录" selected={settings.approvalPolicy === "on-request"} onChange={(value) => onSettingsChange({ approvalPolicy: value ? "on-request" : "never" })} /><ToggleRow label="导出后保存版本" selected={settings.workspace.autoSaveVersions} onChange={(value) => updateWorkspace({ autoSaveVersions: value })} /></div></section>;
  if (section === "browser") return <section className="settings-section"><SectionHeading icon={RiGlobalLine} title="浏览器" description="网页预览与外部资料访问使用同一套联网和审批边界。" /><div className="settings-options"><ToggleRow label="允许网页访问网络" detail="预览中的页面可以加载外部资源" selected={settings.networkAccess} onChange={(value) => onSettingsChange({ networkAccess: value })} /><ToggleRow label="启用 Web Search" detail="允许 Agent 查找外部资料并带回来源" selected={settings.webSearch} onChange={(value) => { updateTool("web-search", value); onSettingsChange({ webSearch: value }); }} /><ChoiceField label="外部操作审批" value={settings.approvalPolicy} options={[{ value: "on-request", label: "每次请求确认" }, { value: "never", label: "不请求确认" }]} onChange={(value) => onSettingsChange({ approvalPolicy: value as AgentSettings["approvalPolicy"] })} /></div></section>;
  if (section === "hooks") return <section className="settings-section"><SectionHeading icon={RiRefreshLine} title="钩子与事件" description="把 Agent 的运行事件记录成可追踪的时间线，便于恢复和排查。" /><div className="settings-options"><ToggleRow label="记录 Agent 事件" detail="工具调用、审批、版本保存和错误都会进入事件流" selected={settings.eventLogging} onChange={(value) => onSettingsChange({ eventLogging: value })} /><ToggleRow label="运行前恢复会话" detail="重新打开项目时保留上一次未完成任务" selected={settings.resumeSessions} onChange={(value) => onSettingsChange({ resumeSessions: value })} /><ToggleRow label="上下文超限时自动压缩" detail="在继续调用模型前整理旧消息和工具结果" selected={settings.autoContextCompaction} onChange={(value) => onSettingsChange({ autoContextCompaction: value })} /></div><div className="event-hook-list"><div><span>会话开始</span><strong>{settings.eventLogging ? "记录" : "跳过"}</strong></div><div><span>工具调用</span><strong>{settings.eventLogging ? "记录" : "跳过"}</strong></div><div><span>版本生成</span><strong>{settings.workspace.autoSaveVersions ? "自动保存" : "手动保存"}</strong></div></div></section>;
  if (section === "connections") return <section className="settings-section"><SectionHeading icon={RiRefreshLine} title="连接状态" description="每个模型和 MCP 连接都在这里显示实际配置状态。" /><div className="connection-status-list">{settings.providers.map((provider) => <ConnectionRow key={provider.id} label={provider.name} detail={`${provider.baseUrl || "未填写 API 地址"} · ${provider.model || "未填写模型"}`} status={provider.status === "ready" ? "已连接" : provider.apiKey ? "待验证" : "未配置"} enabled={provider.enabled} onChange={(value) => onSettingsChange({ providers: settings.providers.map((item) => item.id === provider.id ? { ...item, enabled: value } : item) })} />)}{settings.mcpServers.map((server) => <ConnectionRow key={server.id} label={server.name} detail={`${server.transport.toUpperCase()} · ${server.endpoint}`} status={server.status === "connected" ? "已连接" : "未连接"} enabled={server.enabled} onChange={(value) => onSettingsChange({ mcpServers: settings.mcpServers.map((item) => item.id === server.id ? { ...item, enabled: value, status: value ? "connected" : "disconnected" } : item) })} />)}</div></section>;
  if (section === "git") return <section className="settings-section"><SectionHeading icon={RiCodeBoxLine} title="Git 与版本" description="Magic Code 的作品快照和项目 Git 工作流各自独立，但可以共享修改边界。" /><div className="settings-options"><ToggleRow label="启用版本管理工具" detail="让 Agent 在修改前创建可回退快照" selected={Boolean(settings.tools["version-control"])} onChange={(value) => updateTool("version-control", value)} /><ToggleRow label="自动保存作品版本" detail="每次成功修改后写入新的版本记录" selected={settings.workspace.autoSaveVersions} onChange={(value) => updateWorkspace({ autoSaveVersions: value })} /><ChoiceField label="写入前审批" value={settings.approvalPolicy} options={[{ value: "on-request", label: "需要确认" }, { value: "never", label: "自动写入" }]} onChange={(value) => onSettingsChange({ approvalPolicy: value as AgentSettings["approvalPolicy"] })} /></div><div className="settings-inline-note"><strong>当前边界</strong><span>作品版本回退只影响 Magic Code 预览状态，不会替你提交或覆盖 Git 历史。</span></div></section>;
  if (section === "environment") return <section className="settings-section"><SectionHeading icon={RiTerminalBoxLine} title="运行环境" description="文件、网络和命令能力由沙箱统一约束，危险操作始终优先请求确认。" /><div className="settings-options"><ChoiceField label="文件沙箱" value={settings.sandboxMode} options={[{ value: "read-only", label: "只读项目" }, { value: "workspace-write", label: "项目内可写" }, { value: "danger-full-access", label: "完全访问（谨慎）" }]} onChange={(value) => onSettingsChange({ sandboxMode: value as AgentSettings["sandboxMode"] })} /><ToggleRow label="允许读取项目文件" selected={Boolean(settings.tools["file-read"])} onChange={(value) => updateTool("file-read", value)} /><ToggleRow label="允许写入项目文件" selected={Boolean(settings.tools["file-write"])} onChange={(value) => updateTool("file-write", value)} /><ToggleRow label="允许联网" selected={settings.networkAccess} onChange={(value) => onSettingsChange({ networkAccess: value })} /><ChoiceField label="文件范围" value={settings.workspace.fileScope} options={[{ value: "project", label: "仅当前项目" }, { value: "project-and-children", label: "项目及子目录" }]} onChange={(value) => updateWorkspace({ fileScope: value as AgentSettings["workspace"]["fileScope"] })} /></div></section>;
  return null;
}
